<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="VAPW10000000164" name="BlueCoat Threat pulse Service Tests " tests="1" failures="1" timestamp="12 Sep 2016 04:36:37 GMT" time="4.913" errors="0">
  <testcase name="bluecoatcloud_DirectProvider_withoutPayload_tests" time="2.974" classname="com.bluecoatcloud.threatpulse.tests.BlueCoatThreatPulseTest">
    <failure type="java.lang.AssertionError" message="No response from API. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: No response from API. expected [true] but found [false]
	at com.bluecoatcloud.threatpulse.tests.BlueCoatThreatPulseTest.bluecoatcloud_DirectProvider_withoutPayload_tests(BlueCoatThreatPulseTest.java:433)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- bluecoatcloud_DirectProvider_withoutPayload_tests -->
</testsuite> <!-- BlueCoat Threat pulse Service Tests  -->
